services:
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  zookeeper:
    container_name: zookeeper
    image: felipeagger/kafka-zookeeper:2.12
    restart: always
    ports:
      - 2181:2181

  kafka:
    container_name: kafka
    image: felipeagger/kafka-broker:2.12
    depends_on:
      - zookeeper
    restart: always
    ports:
      - 9092:9092